import type { Metadata } from "next";
import "./globals.css";
import Nav from '@/components/Nav/index'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ fontSize: 87.5 }}>
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"></meta>
      <body className="app-wrapper">
        <div className="g-wrap">
          <div className="app-sidebar">
            <div className="app-left-menu sidebar-container">
              <div className="left-menu-top">
                <a className="logo-lol logo-lol-big"></a>
                <div className="left-menu-tools-bar">
                  <a title="攻略中心-英雄联盟官方网站-腾讯游戏" rel="sidebar">
                    <i className="icon icon-collect"></i>
                    <span>添加收藏</span>
                  </a>
                </div>
              </div>
              <Nav />
              <div className="left-menu-bottom">
                <a className="icon-left-menu-expand"></a>
              </div>
            </div>
          </div>
          <div className="app-main">
            <div className="main-container">
            {children}
          </div>
          </div>
        </div>
      </body>
    </html >
  );
}
